import { IData } from "@/interfaces"

export const sampleData: IData[] = [
  {
    "link": "http://sanders.org/",
    "ar_no": "c9970063-0dc8-4345-aea1-eccafb50e5c0",
    "ar_category": "Category A",
    "area": "Area 3",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 3",
    "affected_item": "character",
    "level": 4,
    "date_reported": "2024-08-28",
    "detection_process": "Personal factor would.",
    "function": "Function 3",
    "in_charge": "Corey Page",
    "self_resolve_car": "True",
    "car_no": "19715d58-8963-494d-ae79-377d859cb42a",
    "status": "In Progress",
    "countermeasure": "Measure 1",
    "fanout": false,
    "remarks": "Arm design add their audience.",
    "month": 8,
    "timestamp": new Date("2024-08-28 16:29:52")
  },
  {
    "link": "https://jackson-perez.info/",
    "ar_no": "cf942821-644f-4670-8bde-ee3e7ba658a8",
    "ar_category": "Category A",
    "area": "Area 1",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 3",
    "affected_item": "adult",
    "level": 5,
    "date_reported": "2024-01-30",
    "detection_process": "Just civil Mr truth trip.",
    "function": "Function 1",
    "in_charge": "Katherine Holmes",
    "self_resolve_car": "True",
    "car_no": "1d421f1c-dfbd-4a53-8147-92f6019a4267",
    "status": "Closed",
    "countermeasure": "Measure 2",
    "fanout": false,
    "remarks": "Local space toward machine appear story.",
    "month": 1,
    "timestamp": new Date("2024-01-30 14:48:36")
  },
  {
    "link": "https://www.stephenson.com/",
    "ar_no": "26344628-c024-4023-9689-31efe1f4b06e",
    "ar_category": "Category C",
    "area": "Area 3",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 2",
    "affected_item": "here",
    "level": 4,
    "date_reported": "2024-09-15",
    "detection_process": "Then sit one him protect program woman.",
    "function": "Function 3",
    "in_charge": "Rose Whitehead",
    "self_resolve_car": "False",
    "car_no": "a6ed5ac4-548a-48a4-a119-ce1987273ba4",
    "status": "Open",
    "countermeasure": "Measure 2",
    "fanout": true,
    "remarks": "Congress admit south difference.",
    "month": 9,
    "timestamp": new Date("2024-09-15 19:38:11")
  },
  {
    "link": "http://www.johnson.com/",
    "ar_no": "3091228d-8136-4e9a-b6e3-933ecb77a28f",
    "ar_category": "Category B",
    "area": "Area 3",
    "abnormality": "Abnormality 1",
    "nature_of_abn": "Nature 1",
    "affected_item": "speak",
    "level": 2,
    "date_reported": "2024-02-07",
    "detection_process": "Prepare wind successful us PM production piece.",
    "function": "Function 3",
    "in_charge": "Jason Russo",
    "self_resolve_car": "False",
    "car_no": "47677f12-1d41-4373-8994-683b55832f82",
    "status": "In Progress",
    "countermeasure": "Measure 2",
    "fanout": false,
    "remarks": "Push box side.",
    "month": 2,
    "timestamp": new Date("2024-02-07 07:50:53")
  },
  {
    "link": "http://martinez-boyer.com/",
    "ar_no": "7f6114cc-2bb6-4d90-842a-0bcf7f2a5b97",
    "ar_category": "Category A",
    "area": "Area 3",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 3",
    "affected_item": "realize",
    "level": 5,
    "date_reported": "2024-02-06",
    "detection_process": "Rather expert safe military late.",
    "function": "Function 3",
    "in_charge": "Mary Sanders",
    "self_resolve_car": "False",
    "car_no": "5425d78c-d6fb-4974-b207-ed877b850ffa",
    "status": "Closed",
    "countermeasure": "Measure 1",
    "fanout": false,
    "remarks": "I someone party collection window.",
    "month": 2,
    "timestamp": new Date("2024-02-06 04:48:52")
  },
  {
    "link": "http://www.kelly-cole.biz/",
    "ar_no": "d224d2ee-4863-4f69-9163-e7fda6f8904f",
    "ar_category": "Category A",
    "area": "Area 2",
    "abnormality": "Abnormality 2",
    "nature_of_abn": "Nature 3",
    "affected_item": "cut",
    "level": 1,
    "date_reported": "2024-12-06",
    "detection_process": "Two best condition debate stuff think.",
    "function": "Function 1",
    "in_charge": "Colleen Johnson",
    "self_resolve_car": "True",
    "car_no": "8bda0116-1a5b-4572-997c-e316f08d09f7",
    "status": "Closed",
    "countermeasure": "Measure 3",
    "fanout": false,
    "remarks": "Person morning expert fish often federal expert.",
    "month": 12,
    "timestamp": new Date("2024-12-06 13:48:49")
  },
  {
    "link": "https://kelly.com/",
    "ar_no": "6c1df5d1-1a40-4949-bca8-76a0aeb26a7e",
    "ar_category": "Category C",
    "area": "Area 1",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 3",
    "affected_item": "appear",
    "level": 5,
    "date_reported": "2024-05-13",
    "detection_process": "Level daughter catch material.",
    "function": "Function 1",
    "in_charge": "Joseph Smith",
    "self_resolve_car": "True",
    "car_no": "b215e6df-22cd-47a8-97c8-83e3a5d4cd97",
    "status": "Open",
    "countermeasure": "Measure 3",
    "fanout": true,
    "remarks": "Participant government what friend possible.",
    "month": 5,
    "timestamp": new Date("2024-05-13 14:40:56")
  },
  {
    "link": "http://www.smith-walker.com/",
    "ar_no": "79446327-f404-4ce7-9a56-dbf7a128a1d2",
    "ar_category": "Category C",
    "area": "Area 1",
    "abnormality": "Abnormality 2",
    "nature_of_abn": "Nature 2",
    "affected_item": "fine",
    "level": 2,
    "date_reported": "2024-02-23",
    "detection_process": "Professional protect sound movement finally.",
    "function": "Function 2",
    "in_charge": "Charlene Boyd",
    "self_resolve_car": "False",
    "car_no": "d066adac-0c98-407c-9b22-cf30f950f79e",
    "status": "Closed",
    "countermeasure": "Measure 2",
    "fanout": true,
    "remarks": "Rule do day affect decide how.",
    "month": 2,
    "timestamp": new Date("2024-02-23 04:51:46")
  },
  {
    "link": "http://www.miller-willis.com/",
    "ar_no": "a8b6d792-a1e3-43d9-ac63-1cdd2fd68abc",
    "ar_category": "Category C",
    "area": "Area 2",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 2",
    "affected_item": "item",
    "level": 5,
    "date_reported": "2024-09-20",
    "detection_process": "Charge perform item themselves her hope.",
    "function": "Function 3",
    "in_charge": "Franklin George",
    "self_resolve_car": "False",
    "car_no": "f30a7af6-d111-4a49-b244-6edbac1c9b9d",
    "status": "Open",
    "countermeasure": "Measure 3",
    "fanout": true,
    "remarks": "Store little value even.",
    "month": 9,
    "timestamp": new Date("2024-09-20 00:22:41")
  },
  {
    "link": "http://liu-patterson.net/",
    "ar_no": "a989207d-0ea6-4798-ae7a-289fd6d4d4e9",
    "ar_category": "Category A",
    "area": "Area 2",
    "abnormality": "Abnormality 1",
    "nature_of_abn": "Nature 1",
    "affected_item": "speak",
    "level": 1,
    "date_reported": "2024-04-09",
    "detection_process": "Message describe detail night job born those.",
    "function": "Function 1",
    "in_charge": "Marco Jones",
    "self_resolve_car": "False",
    "car_no": "e33acdc5-0cdc-4062-90a4-0f3e3c2a46da",
    "status": "Open",
    "countermeasure": "Measure 2",
    "fanout": true,
    "remarks": "High defense message family word different law.",
    "month": 4,
    "timestamp": new Date("2024-04-09 19:29:54")
  },
  {
    "link": "https://smith-knight.biz/",
    "ar_no": "b3a9b324-0e85-4636-8851-368a542d5caf",
    "ar_category": "Category A",
    "area": "Area 1",
    "abnormality": "Abnormality 2",
    "nature_of_abn": "Nature 3",
    "affected_item": "husband",
    "level": 5,
    "date_reported": "2024-04-13",
    "detection_process": "Two hotel Democrat ball late sit theory.",
    "function": "Function 2",
    "in_charge": "Laura Kennedy",
    "self_resolve_car": "False",
    "car_no": "ea715b3c-4338-4363-80a8-cca60fcb7d8a",
    "status": "Closed",
    "countermeasure": "Measure 2",
    "fanout": true,
    "remarks": "Financial arm smile.",
    "month": 4,
    "timestamp": new Date("2024-04-13 12:59:11")
  },
  {
    "link": "https://www.griffin.com/",
    "ar_no": "1e8f9677-a3bd-438d-8875-d4fa1962561f",
    "ar_category": "Category B",
    "area": "Area 2",
    "abnormality": "Abnormality 2",
    "nature_of_abn": "Nature 3",
    "affected_item": "car",
    "level": 5,
    "date_reported": "2024-08-28",
    "detection_process": "Report anyone manager.",
    "function": "Function 2",
    "in_charge": "Adam Thomas",
    "self_resolve_car": "True",
    "car_no": "2bc1b08f-af6a-4562-a105-70170cef1dd8",
    "status": "Closed",
    "countermeasure": "Measure 3",
    "fanout": true,
    "remarks": "Than region effort former want pass.",
    "month": 8,
    "timestamp": new Date("2024-08-28 19:27:05")
  },
  {
    "link": "https://www.bishop-contreras.biz/",
    "ar_no": "caa1ab75-e221-4508-8062-1b1b3f26c285",
    "ar_category": "Category B",
    "area": "Area 1",
    "abnormality": "Abnormality 2",
    "nature_of_abn": "Nature 1",
    "affected_item": "none",
    "level": 3,
    "date_reported": "2024-02-16",
    "detection_process": "Sure effect short follow bar.",
    "function": "Function 3",
    "in_charge": "Lisa King",
    "self_resolve_car": "True",
    "car_no": "e6fe6c97-adab-48a2-ba44-8fef869a11d7",
    "status": "In Progress",
    "countermeasure": "Measure 3",
    "fanout": false,
    "remarks": "Result charge cup price assume.",
    "month": 2,
    "timestamp": new Date("2024-02-16 21:16:30")
  },
  {
    "link": "https://conway-fox.com/",
    "ar_no": "67107478-ab09-42bb-ac68-2869e1b64e97",
    "ar_category": "Category C",
    "area": "Area 2",
    "abnormality": "Abnormality 2",
    "nature_of_abn": "Nature 3",
    "affected_item": "appear",
    "level": 5,
    "date_reported": "2024-01-31",
    "detection_process": "Fall enjoy of raise.",
    "function": "Function 2",
    "in_charge": "Brittany Carter",
    "self_resolve_car": "True",
    "car_no": "0e788f38-77e2-43f6-af1b-21f341b06650",
    "status": "Open",
    "countermeasure": "Measure 2",
    "fanout": false,
    "remarks": "Thing front somebody group accept approach.",
    "month": 1,
    "timestamp": new Date("2024-01-31 15:59:13")
  },
  {
    "link": "http://www.cox.info/",
    "ar_no": "35dce574-7fc7-4622-8366-d3e5d907d847",
    "ar_category": "Category A",
    "area": "Area 1",
    "abnormality": "Abnormality 1",
    "nature_of_abn": "Nature 3",
    "affected_item": "really",
    "level": 5,
    "date_reported": "2024-09-05",
    "detection_process": "Time future military less hand front.",
    "function": "Function 2",
    "in_charge": "Amy Gentry",
    "self_resolve_car": "False",
    "car_no": "e1374377-994b-4320-baf3-8a9c9aace49c",
    "status": "Open",
    "countermeasure": "Measure 2",
    "fanout": true,
    "remarks": "Price visit wear.",
    "month": 9,
    "timestamp": new Date("2024-09-05 03:18:40")
  },
  {
    "link": "https://davis.com/",
    "ar_no": "aca0366a-9a4e-4754-b9c1-66b7bf6c31ea",
    "ar_category": "Category C",
    "area": "Area 2",
    "abnormality": "Abnormality 1",
    "nature_of_abn": "Nature 3",
    "affected_item": "start",
    "level": 1,
    "date_reported": "2024-05-15",
    "detection_process": "Computer allow every guess on big language price.",
    "function": "Function 1",
    "in_charge": "Bridget Holland",
    "self_resolve_car": "False",
    "car_no": "adfe67c1-2dda-4bf3-82bd-8b7f063cfa3e",
    "status": "Open",
    "countermeasure": "Measure 1",
    "fanout": true,
    "remarks": "Billion number general long wall nearly.",
    "month": 5,
    "timestamp": new Date("2024-05-15 09:58:48")
  },
  {
    "link": "https://phillips-coleman.com/",
    "ar_no": "bef81d47-38e7-4abf-9acf-e1f78df539cf",
    "ar_category": "Category A",
    "area": "Area 3",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 2",
    "affected_item": "hear",
    "level": 3,
    "date_reported": "2024-07-25",
    "detection_process": "Thought wife large section.",
    "function": "Function 2",
    "in_charge": "Gary Crawford",
    "self_resolve_car": "True",
    "car_no": "9e21b4ff-bcf8-46c0-9354-8ad8384c3060",
    "status": "Closed",
    "countermeasure": "Measure 1",
    "fanout": true,
    "remarks": "Central process another together few.",
    "month": 7,
    "timestamp": new Date("2024-07-25 16:40:52")
  },
  {
    "link": "https://johnson-patton.com/",
    "ar_no": "88320199-cf12-422f-a9c0-48ec03863668",
    "ar_category": "Category B",
    "area": "Area 1",
    "abnormality": "Abnormality 1",
    "nature_of_abn": "Nature 3",
    "affected_item": "leader",
    "level": 3,
    "date_reported": "2024-02-10",
    "detection_process": "Save trip matter financial second.",
    "function": "Function 3",
    "in_charge": "Jesse Martinez",
    "self_resolve_car": "True",
    "car_no": "31be1fb2-d6ca-477a-bbbc-39bd511ed91d",
    "status": "Closed",
    "countermeasure": "Measure 3",
    "fanout": true,
    "remarks": "The reach official understand process.",
    "month": 2,
    "timestamp": new Date("2024-02-10 12:11:55")
  },
  {
    "link": "https://jones-floyd.com/",
    "ar_no": "d0afd534-3d9b-440f-be5e-052e73516d9f",
    "ar_category": "Category A",
    "area": "Area 1",
    "abnormality": "Abnormality 3",
    "nature_of_abn": "Nature 1",
    "affected_item": "quite",
    "level": 4,
    "date_reported": "2024-04-12",
    "detection_process": "Adult create hotel back look quickly.",
    "function": "Function 2",
    "in_charge": "Lindsay Terry",
    "self_resolve_car": "True",
    "car_no": "ef799f56-03fd-4fd1-9dfc-dad16ca23480",
    "status": "Open",
    "countermeasure": "Measure 3",
    "fanout": true,
    "remarks": "Dinner character occur speech. Card maybe deal.",
    "month": 4,
    "timestamp": new Date("2024-04-12 13:42:34")
  },
  {
    "link": "https://www.brown.com/",
    "ar_no": "da4e0dc4-0351-4589-9aaa-8f66af6b0a05",
    "ar_category": "Category A",
    "area": "Area 2",
    "abnormality": "Abnormality 1",
    "nature_of_abn": "Nature 1",
    "affected_item": "president",
    "level": 3,
    "date_reported": "2024-05-24",
    "detection_process": "Great together reach.",
    "function": "Function 3",
    "in_charge": "Brett Miller",
    "self_resolve_car": "False",
    "car_no": "1633c940-c922-46ee-89a4-96f18c9d6cda",
    "status": "Open",
    "countermeasure": "Measure 3",
    "fanout": true,
    "remarks": "Despite market serve every business.",
    "month": 5,
    "timestamp": new Date("2024-05-24 19:54:26")
  }
]